class ErrnoException
!!!2032795.java!!!	ErrnoException(inout functionName : String, in errno : int)
        this.functionName = functionName;
        this.errno = errno;
!!!2032923.java!!!	ErrnoException(inout functionName : String, in errno : int, inout cause : Throwable)
        super(cause);
        this.functionName = functionName;
        this.errno = errno;
!!!2033051.java!!!	getMessage() : String
        String errnoName = OsConstants.errnoName(errno);
        if (errnoName == null) {
            errnoName = "errno " + errno;
        }
        String description = Libcore.os.strerror(errno);
        return functionName + " failed: " + errnoName + " (" + description + ")";
!!!2033179.java!!!	rethrowAsIOException() : IOException
        IOException newException = new IOException(getMessage());
        newException.initCause(this);
        throw newException;
!!!2033307.java!!!	rethrowAsSocketException() : SocketException
        throw new SocketException(getMessage(), this);
